# Generated by Django 5.1.4 on 2025-03-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_token_created',
        ),
    ]
