# Generated by Django 5.1.4 on 2025-03-08 22:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('finished_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('includes_branding', models.BooleanField(default=False)),
                ('includes_frontend', models.BooleanField(default=False)),
                ('includes_backend', models.BooleanField(default=False)),
                ('includes_dashboard', models.BooleanField(default=False)),
                ('includes_media', models.BooleanField(default=False)),
                ('includes_sales', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='PageDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('page_sections', models.TextField(blank=True, help_text='What do you want to have in each section? Is it a set of pictures, or some text about a certain topic?', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_designs', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='MediaPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_media_manager', models.BooleanField(default=False)),
                ('media_organization', models.TextField(blank=True, help_text='How would you like to manage your media? Would you like to split it into different Categories, Genres, Places, and People?', null=True)),
                ('needs_media_storage', models.BooleanField(default=False)),
                ('media_storage_details', models.TextField(blank=True, help_text='What are your media storage requirements?', null=True)),
                ('needs_data_center', models.BooleanField(default=False)),
                ('data_center_details', models.TextField(blank=True, help_text='What are your data center requirements?', null=True)),
                ('has_images', models.BooleanField(default=False)),
                ('has_audio', models.BooleanField(default=False)),
                ('has_video', models.BooleanField(default=False)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_package', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='FrontEndPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_web_template', models.BooleanField(default=False)),
                ('web_template_details', models.TextField(blank=True, help_text='What kind of web template do you need?', null=True)),
                ('needs_dynamic_website', models.BooleanField(default=False)),
                ('dynamic_website_details', models.TextField(blank=True, help_text='What are your requirements for the dynamic website/web-application?', null=True)),
                ('page_content_structure', models.TextField(blank=True, help_text='What would you like to have on your pages? Break it down into sections.', null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frontend_package', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentation_details', models.TextField(blank=True, help_text='Think about the most important aspects in the application that need documentation', null=True)),
                ('licensing_details', models.TextField(blank=True, help_text='Details about licensing requirements', null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_admin_dashboard', models.BooleanField(default=False)),
                ('custom_django_dashboard', models.BooleanField(default=False)),
                ('custom_template_design', models.BooleanField(default=False)),
                ('dashboard_details', models.TextField(blank=True, help_text='What features do you need in your dashboard? (Statistics, Frontend Content Editor, etc.)', null=True)),
                ('needs_content_manager', models.BooleanField(default=False)),
                ('needs_custom_fields', models.BooleanField(default=False)),
                ('needs_page_template_fields', models.BooleanField(default=False)),
                ('content_manager_details', models.TextField(blank=True, help_text='What would you like to edit? Are there going to be posts or articles like a blog? Are they a fixed set of text? Or will it be different types of content?', null=True)),
                ('needs_statistics', models.BooleanField(default=False)),
                ('statistics_details', models.TextField(blank=True, help_text='What type of statistics would you like to see about your audience?', null=True)),
                ('needs_progress_tracking', models.BooleanField(default=False)),
                ('progress_tracking_details', models.TextField(blank=True, help_text='Details about timeline and progress bar requirements', null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_package', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='BrandingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_brand_design', models.BooleanField(default=False)),
                ('brand_design_details', models.TextField(blank=True, help_text='What are your brand design requirements?', null=True)),
                ('needs_digital_design', models.BooleanField(default=False)),
                ('digital_design_details', models.TextField(blank=True, help_text='What are your digital design requirements?', null=True)),
                ('needs_paper_design', models.BooleanField(default=False)),
                ('paper_design_details', models.TextField(blank=True, help_text='What are your paper design requirements?', null=True)),
                ('process_simplification', models.TextField(blank=True, help_text="What are ways to make the process easier to achieve the end result? Do you have to show any Identification/Information to show it's a legit Business?", null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branding_package', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='BackEndPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_client_models', models.BooleanField(default=False)),
                ('client_models_details', models.TextField(blank=True, help_text='What kind of client models do you need?', null=True)),
                ('needs_organized_models', models.BooleanField(default=False)),
                ('organized_models_details', models.TextField(blank=True, help_text='How would you like your client models organized?', null=True)),
                ('needs_base_app', models.BooleanField(default=False)),
                ('base_app_details', models.TextField(blank=True, help_text='What functionality do you need in the base app (User Base, Groups, Authentication)?', null=True)),
                ('main_database_name', models.CharField(blank=True, help_text='Name of your main database app where client models are stored', max_length=100, null=True)),
                ('user_data_app_name', models.CharField(blank=True, help_text='Name of app for user permissions and other functionality', max_length=100, null=True)),
                ('data_collection_requirements', models.TextField(blank=True, help_text='What do you want to learn about your audience?', null=True)),
                ('needs_rest_api', models.BooleanField(default=False)),
                ('needs_endpoints', models.BooleanField(default=False)),
                ('needs_custom_urls', models.BooleanField(default=False)),
                ('api_details', models.TextField(blank=True, help_text='Details about your API requirements (serializers, endpoints, URLs)', null=True)),
                ('main_features', models.TextField(blank=True, help_text='What are the main Functions or Features of the application? Do they have any Sub-Functions or Paid Features for the Clients and Consumers?', null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('administrator_roles', models.TextField(blank=True, help_text='Who is the main Administrator? Do they have any Employees or Sub-Admins? Is there someone who challenges the Project?', null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backend_package', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('application_type', models.CharField(max_length=100)),
                ('application_details', models.TextField(blank=True, null=True)),
                ('priority_level', models.IntegerField(default=0)),
                ('is_addressed', models.BooleanField(default=False)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='SalesPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('needs_sales_management', models.BooleanField(default=False)),
                ('needs_expense_management', models.BooleanField(default=False)),
                ('needs_stock_management', models.BooleanField(default=False)),
                ('needs_sales_dashboard', models.BooleanField(default=False)),
                ('custom_sales_dashboard', models.BooleanField(default=False)),
                ('custom_sales_template', models.BooleanField(default=False)),
                ('financial_management_details', models.TextField(blank=True, help_text='Would you like to manage your Finances through the website?', null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_package', to='projects.project')),
            ],
        ),
    ]
